# -*- coding: utf-8 -*-
"""weighbridge_dashboard_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j060gwiB2tI-_T7KSxoClNTzJAT0bGxd
"""

import streamlit as st
import pandas as pd
import folium
from streamlit_folium import folium_static
import plotly.express as px
from datetime import datetime

# Sample data
data = [
  {
    "scale_id": "SCL001",
    "location_name": "Nairobi",
    "latitude": -1.2921,
    "longitude": 36.8219,
    "last_maintenance": "04/10/25",
    "status": "operational",
    "last_weight_reading": 1234.5,
    "last_updated": "2025-05-23 10:20:00"
  },
  {
    "scale_id": "SCL002",
    "location_name": "Mombasa",
    "latitude": -4.0435,
    "longitude": 39.6682,
    "last_maintenance": "03/15/25",
    "status": "offline",
    "last_weight_reading": 0,
    "last_updated": "2025-05-20 08:15:00"
  },
  {
    "scale_id": "SCL003",
    "location_name": "Kisumu",
    "latitude": -0.0917,
    "longitude": 34.7679,
    "last_maintenance": "02/28/25",
    "status": "error",
    "last_weight_reading": 0,
    "last_updated": "2025-05-21 12:45:00"
  },
  {
    "scale_id": "SCL004",
    "location_name": "Nairobi",
    "latitude": -1.285255,
    "longitude": 39.289988,
    "last_maintenance": "02/11/25",
    "status": "offline",
    "last_weight_reading": 2169,
    "last_updated": "2025-05-28 06:26:00"
  },
  {
    "scale_id": "SCL005",
    "location_name": "Nairobi",
    "latitude": -0.49397,
    "longitude": 36.426932,
    "last_maintenance": "01/26/25",
    "status": "offline",
    "last_weight_reading": 731,
    "last_updated": "2025-05-21 00:17:00"
  },
  {
    "scale_id": "SCL006",
    "location_name": "Nairobi",
    "latitude": -4.029121,
    "longitude": 36.306258,
    "last_maintenance": "05/3/25",
    "status": "error",
    "last_weight_reading": 332,
    "last_updated": "2025-05-28 11:24:00"
  },
  {
    "scale_id": "SCL007",
    "location_name": "Nairobi",
    "latitude": -1.410492,
    "longitude": 34.133942,
    "last_maintenance": "05/29/25",
    "status": "operational",
    "last_weight_reading": 1763.3,
    "last_updated": "2025-05-19 16:23:00"
  },
  {
    "scale_id": "SCL008",
    "location_name": "Nairobi",
    "latitude": -2.715293,
    "longitude": 38.485752,
    "last_maintenance": "03/14/25",
    "status": "operational",
    "last_weight_reading": 94.7,
    "last_updated": "2025-05-28 19:05:00"
  },
  {
    "scale_id": "SCL009",
    "location_name": "Mombasa",
    "latitude": -1.924413,
    "longitude": 39.542779,
    "last_maintenance": "04/19/25",
    "status": "operational",
    "last_weight_reading": 2450.8,
    "last_updated": "2025-05-27 17:52:00"
  },
  {
    "scale_id": "SCL010",
    "location_name": "Nairobi",
    "latitude": 0.728156,
    "longitude": 38.710535,
    "last_maintenance": "03/13/25",
    "status": "operational",
    "last_weight_reading": 875.8,
    "last_updated": "2025-05-24 20:04:00"
  },
  {
    "scale_id": "SCL011",
    "location_name": "Nairobi",
    "latitude": -4.438938,
    "longitude": 37.065029,
    "last_maintenance": "01/7/25",
    "status": "operational",
    "last_weight_reading": 1316.2,
    "last_updated": "2025-05-21 05:32:00"
  },
  {
    "scale_id": "SCL012",
    "location_name": "Nairobi",
    "latitude": -1.60664,
    "longitude": 38.744912,
    "last_maintenance": "05/9/25",
    "status": "operational",
    "last_weight_reading": 2190.4,
    "last_updated": "2025-05-14 07:17:00"
  },
  {
    "scale_id": "SCL013",
    "location_name": "Nairobi",
    "latitude": -3.211361,
    "longitude": 34.463566,
    "last_maintenance": "04/28/25",
    "status": "operational",
    "last_weight_reading": 1544.3,
    "last_updated": "2025-05-29 05:32:00"
  },
  {
    "scale_id": "SCL014",
    "location_name": "Nairobi",
    "latitude": -1.869368,
    "longitude": 39.256782,
    "last_maintenance": "01/26/25",
    "status": "error",
    "last_weight_reading": 1191,
    "last_updated": "2025-05-03 04:02:00"
  },
  {
    "scale_id": "SCL015",
    "location_name": "Nairobi",
    "latitude": -4.444655,
    "longitude": 40.863078,
    "last_maintenance": "04/13/25",
    "status": "offline",
    "last_weight_reading": 1396,
    "last_updated": "2025-05-11 19:31:00"
  },
  {
    "scale_id": "SCL016",
    "location_name": "Nairobi",
    "latitude": 0.231832,
    "longitude": 35.98759,
    "last_maintenance": "02/7/25",
    "status": "offline",
    "last_weight_reading": 2473,
    "last_updated": "2025-05-04 03:29:00"
  },
  {
    "scale_id": "SCL017",
    "location_name": "Mombasa",
    "latitude": -0.84431,
    "longitude": 34.362577,
    "last_maintenance": "03/23/25",
    "status": "offline",
    "last_weight_reading": 1507,
    "last_updated": "2025-05-09 21:09:00"
  },
  {
    "scale_id": "SCL018",
    "location_name": "Nairobi",
    "latitude": -2.251763,
    "longitude": 37.22921,
    "last_maintenance": "03/30/25",
    "status": "operational",
    "last_weight_reading": 358.7,
    "last_updated": "2025-05-10 20:55:00"
  },
  {
    "scale_id": "SCL019",
    "location_name": "Kisumu",
    "latitude": 0.464613,
    "longitude": 35.42797,
    "last_maintenance": "02/1/25",
    "status": "offline",
    "last_weight_reading": 948,
    "last_updated": "2025-05-14 18:29:00"
  },
  {
    "scale_id": "SCL020",
    "location_name": "Mombasa",
    "latitude": 0.86727,
    "longitude": 36.960051,
    "last_maintenance": "05/2/25",
    "status": "error",
    "last_weight_reading": 2093,
    "last_updated": "2025-05-18 22:01:00"
  },
  {
    "scale_id": "SCL021",
    "location_name": "Kisumu",
    "latitude": -3.899954,
    "longitude": 39.193189,
    "last_maintenance": "05/19/25",
    "status": "error",
    "last_weight_reading": 26,
    "last_updated": "2025-05-20 05:26:00"
  },
  {
    "scale_id": "SCL022",
    "location_name": "Kisumu",
    "latitude": -1.239852,
    "longitude": 39.757096,
    "last_maintenance": "04/12/25",
    "status": "error",
    "last_weight_reading": 1239,
    "last_updated": "2025-05-09 20:42:00"
  },
  {
    "scale_id": "SCL023",
    "location_name": "Nairobi",
    "latitude": -2.148432,
    "longitude": 34.604698,
    "last_maintenance": "05/23/25",
    "status": "offline",
    "last_weight_reading": 2100,
    "last_updated": "2025-05-21 03:53:00"
  },
  {
    "scale_id": "SCL024",
    "location_name": "Kisumu",
    "latitude": -1.03633,
    "longitude": 34.904499,
    "last_maintenance": "04/13/25",
    "status": "operational",
    "last_weight_reading": 949.9,
    "last_updated": "2025-05-27 07:38:00"
  },
  {
    "scale_id": "SCL025",
    "location_name": "Kisumu",
    "latitude": -0.733995,
    "longitude": 38.774403,
    "last_maintenance": "05/8/25",
    "status": "offline",
    "last_weight_reading": 923,
    "last_updated": "2025-05-29 03:28:00"
  },
  {
    "scale_id": "SCL026",
    "location_name": "Mombasa",
    "latitude": -4.270518,
    "longitude": 39.891852,
    "last_maintenance": "01/24/25",
    "status": "offline",
    "last_weight_reading": 620,
    "last_updated": "2025-05-20 08:28:00"
  },
  {
    "scale_id": "SCL027",
    "location_name": "Kisumu",
    "latitude": -3.849004,
    "longitude": 40.072061,
    "last_maintenance": "02/13/25",
    "status": "offline",
    "last_weight_reading": 1153,
    "last_updated": "2025-05-13 15:36:00"
  },
  {
    "scale_id": "SCL028",
    "location_name": "Kisumu",
    "latitude": -2.464456,
    "longitude": 40.385801,
    "last_maintenance": "03/6/25",
    "status": "error",
    "last_weight_reading": 255,
    "last_updated": "2025-05-14 13:26:00"
  },
  {
    "scale_id": "SCL029",
    "location_name": "Nairobi",
    "latitude": -3.227854,
    "longitude": 38.510051,
    "last_maintenance": "02/6/25",
    "status": "offline",
    "last_weight_reading": 1302,
    "last_updated": "2025-05-06 19:01:00"
  },
  {
    "scale_id": "SCL030",
    "location_name": "Mombasa",
    "latitude": -2.829182,
    "longitude": 35.063575,
    "last_maintenance": "01/18/25",
    "status": "offline",
    "last_weight_reading": 1758,
    "last_updated": "2025-05-29 08:20:00"
  },
  {
    "scale_id": "SCL031",
    "location_name": "Mombasa",
    "latitude": -2.246955,
    "longitude": 39.803439,
    "last_maintenance": "05/1/25",
    "status": "offline",
    "last_weight_reading": 1885,
    "last_updated": "2025-05-03 04:53:00"
  },
  {
    "scale_id": "SCL032",
    "location_name": "Kisumu",
    "latitude": -1.983772,
    "longitude": 37.007618,
    "last_maintenance": "04/5/25",
    "status": "operational",
    "last_weight_reading": 705.5,
    "last_updated": "2025-05-04 16:16:00"
  },
  {
    "scale_id": "SCL033",
    "location_name": "Nairobi",
    "latitude": -1.000728,
    "longitude": 39.990664,
    "last_maintenance": "03/20/25",
    "status": "error",
    "last_weight_reading": 2153,
    "last_updated": "2025-05-04 20:13:00"
  },
  {
    "scale_id": "SCL034",
    "location_name": "Nairobi",
    "latitude": -4.412616,
    "longitude": 37.46661,
    "last_maintenance": "04/25/25",
    "status": "operational",
    "last_weight_reading": 14.5,
    "last_updated": "2025-05-15 14:05:00"
  },
  {
    "scale_id": "SCL035",
    "location_name": "Kisumu",
    "latitude": -2.282689,
    "longitude": 35.878723,
    "last_maintenance": "05/15/25",
    "status": "error",
    "last_weight_reading": 2268,
    "last_updated": "2025-05-07 00:09:00"
  },
  {
    "scale_id": "SCL036",
    "location_name": "Kisumu",
    "latitude": -1.279555,
    "longitude": 34.224838,
    "last_maintenance": "02/21/25",
    "status": "operational",
    "last_weight_reading": 1021.7,
    "last_updated": "2025-05-05 07:12:00"
  },
  {
    "scale_id": "SCL037",
    "location_name": "Mombasa",
    "latitude": -3.930522,
    "longitude": 40.606217,
    "last_maintenance": "03/22/25",
    "status": "error",
    "last_weight_reading": 1106,
    "last_updated": "2025-05-01 15:50:00"
  },
  {
    "scale_id": "SCL038",
    "location_name": "Kisumu",
    "latitude": -1.836589,
    "longitude": 36.809238,
    "last_maintenance": "03/12/25",
    "status": "offline",
    "last_weight_reading": 1829,
    "last_updated": "2025-05-25 11:24:00"
  },
  {
    "scale_id": "SCL039",
    "location_name": "Mombasa",
    "latitude": -4.472622,
    "longitude": 38.979574,
    "last_maintenance": "01/24/25",
    "status": "error",
    "last_weight_reading": 1002,
    "last_updated": "2025-05-27 08:01:00"
  },
  {
    "scale_id": "SCL040",
    "location_name": "Kisumu",
    "latitude": -2.213713,
    "longitude": 36.957677,
    "last_maintenance": "04/4/25",
    "status": "error",
    "last_weight_reading": 1716,
    "last_updated": "2025-05-10 15:19:00"
  },
  {
    "scale_id": "SCL041",
    "location_name": "Nairobi",
    "latitude": -3.592613,
    "longitude": 38.474219,
    "last_maintenance": "02/4/25",
    "status": "operational",
    "last_weight_reading": 297.4,
    "last_updated": "2025-05-25 18:50:00"
  },
  {
    "scale_id": "SCL042",
    "location_name": "Nairobi",
    "latitude": 0.574045,
    "longitude": 39.102693,
    "last_maintenance": "04/24/25",
    "status": "operational",
    "last_weight_reading": 1011.3,
    "last_updated": "2025-05-09 21:57:00"
  },
  {
    "scale_id": "SCL043",
    "location_name": "Mombasa",
    "latitude": -3.472732,
    "longitude": 34.801713,
    "last_maintenance": "01/19/25",
    "status": "operational",
    "last_weight_reading": 137,
    "last_updated": "2025-05-29 18:15:00"
  },
  {
    "scale_id": "SCL044",
    "location_name": "Nairobi",
    "latitude": 0.008545,
    "longitude": 37.313582,
    "last_maintenance": "05/22/25",
    "status": "error",
    "last_weight_reading": 2078,
    "last_updated": "2025-05-08 15:24:00"
  },
  {
    "scale_id": "SCL045",
    "location_name": "Nairobi",
    "latitude": -1.20902,
    "longitude": 38.404505,
    "last_maintenance": "05/9/25",
    "status": "operational",
    "last_weight_reading": 49.4,
    "last_updated": "2025-05-27 12:55:00"
  },
  {
    "scale_id": "SCL046",
    "location_name": "Nairobi",
    "latitude": 0.620112,
    "longitude": 35.042838,
    "last_maintenance": "01/12/25",
    "status": "offline",
    "last_weight_reading": 1286,
    "last_updated": "2025-05-14 05:30:00"
  },
  {
    "scale_id": "SCL047",
    "location_name": "Mombasa",
    "latitude": -3.312569,
    "longitude": 36.909142,
    "last_maintenance": "04/3/25",
    "status": "operational",
    "last_weight_reading": 2001.2,
    "last_updated": "2025-05-01 00:10:00"
  },
  {
    "scale_id": "SCL048",
    "location_name": "Nairobi",
    "latitude": -0.752165,
    "longitude": 39.333433,
    "last_maintenance": "01/19/25",
    "status": "operational",
    "last_weight_reading": 1396.8,
    "last_updated": "2025-05-08 03:10:00"
  },
  {
    "scale_id": "SCL049",
    "location_name": "Kisumu",
    "latitude": -0.987137,
    "longitude": 39.773415,
    "last_maintenance": "04/1/25",
    "status": "operational",
    "last_weight_reading": 433.4,
    "last_updated": "2025-05-26 10:11:00"
  },
  {
    "scale_id": "SCL050",
    "location_name": "Nairobi",
    "latitude": -0.440453,
    "longitude": 40.057449,
    "last_maintenance": "03/31/25",
    "status": "operational",
    "last_weight_reading": 433.4,
    "last_updated": "2025-05-31 16:19:00"
  },
  {
    "scale_id": "SCL051",
    "location_name": "Mombasa",
    "latitude": -1.180667,
    "longitude": 34.862119,
    "last_maintenance": "05/27/25",
    "status": "offline",
    "last_weight_reading": 128,
    "last_updated": "2025-05-05 03:16:00"
  },
  {
    "scale_id": "SCL052",
    "location_name": "Kisumu",
    "latitude": -4.198246,
    "longitude": 40.060249,
    "last_maintenance": "03/22/25",
    "status": "error",
    "last_weight_reading": 1904,
    "last_updated": "2025-05-17 10:00:00"
  },
  {
    "scale_id": "SCL053",
    "location_name": "Kisumu",
    "latitude": -3.630624,
    "longitude": 40.425686,
    "last_maintenance": "03/18/25",
    "status": "error",
    "last_weight_reading": 159,
    "last_updated": "2025-05-18 07:16:00"
  }
]

# Convert to DataFrame
df = pd.DataFrame(data)

# Convert dates to datetime objects
df['last_maintenance'] = pd.to_datetime(df['last_maintenance'])
df['last_updated'] = pd.to_datetime(df['last_updated'])

# Calculate days since last maintenance
df['days_since_maintenance'] = (datetime.now() - df['last_maintenance']).dt.days

# Dashboard title
st.title("Weighing Scale Monitoring Dashboard")

# Sidebar filters
st.sidebar.header("Filters")
status_filter = st.sidebar.multiselect(
    "Filter by status:",
    options=df['status'].unique(),
    default=df['status'].unique()
)

location_filter = st.sidebar.multiselect(
    "Filter by location:",
    options=df['location_name'].unique(),
    default=df['location_name'].unique()
)

# Apply filters
filtered_df = df[
    (df['status'].isin(status_filter)) &
    (df['location_name'].isin(location_filter))
]

# Display metrics
col1, col2, col3 = st.columns(3)
col1.metric("Total Scales", len(filtered_df))
col2.metric("Operational", len(filtered_df[filtered_df['status'] == 'operational']))
col3.metric("Needing Maintenance", len(filtered_df[filtered_df['days_since_maintenance'] > 60]))

# Interactive map
st.subheader("Scale Locations")
if not filtered_df.empty:
    # Create map centered on Kenya
    m = folium.Map(location=[-0.0236, 37.9062], zoom_start=6)

    # Add markers for each scale
    for idx, row in filtered_df.iterrows():
        # Customize marker color based on status
        if row['status'] == 'operational':
            color = 'green'
        elif row['status'] == 'offline':
            color = 'gray'
        else:
            color = 'red'

        popup_text = f"""
        <b>Scale ID:</b> {row['scale_id']}<br>
        <b>Location:</b> {row['location_name']}<br>
        <b>Status:</b> {row['status']}<br>
        <b>Last Weight:</b> {row['last_weight_reading']} kg<br>
        <b>Last Updated:</b> {row['last_updated'].strftime('%Y-%m-%d %H:%M')}
        """

        folium.Marker(
            location=[row['latitude'], row['longitude']],
            popup=folium.Popup(popup_text, max_width=250),
            icon=folium.Icon(color=color, icon='scale-balanced', prefix='fa')
        ).add_to(m)

    # Display the map
    folium_static(m, width=800, height=500)
else:
    st.warning("No scales match the selected filters.")

# Data table
st.subheader("Scale Data")
st.dataframe(filtered_df.style.applymap(
    lambda x: 'background-color: green' if x == 'operational' else
    ('background-color: red' if x == 'error' else
     'background-color: gray'),
    subset=['status']
))

# Weight readings chart
st.subheader("Weight Readings")
if not filtered_df.empty:
    fig = px.bar(
        filtered_df,
        x='location_name',
        y='last_weight_reading',
        color='status',
        labels={'location_name': 'Location', 'last_weight_reading': 'Weight (kg)'},
        title='Current Weight Readings by Location'
    )
    st.plotly_chart(fig)
else:
    st.warning("No data to display for the selected filters.")

# Maintenance status
st.subheader("Maintenance Status")
if not filtered_df.empty:
    fig = px.scatter(
        filtered_df,
        x='last_maintenance',
        y='location_name',
        color='status',
        size='days_since_maintenance',
        labels={'last_maintenance': 'Last Maintenance Date', 'location_name': 'Location'},
        title='Maintenance Status (Size indicates days since last maintenance)'
    )
    st.plotly_chart(fig)
else:
    st.warning("No data to display for the selected filters.")